package com.toyota.usermanagementservice.dto;

import lombok.*;

/**
 * A DTO class representing a request to create or update a role.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class RoleRequest {

    /**
     * The role name.
     */
    private String role;

    // Getters and setters are generated by Lombok annotations
}
